### ISSUE TITLE
Merge "fff" and "rw" folders

### ISSUE THREAD

**Issue by jamesoshea** [jakobschult/rwapp#21]

**Comment by jamesoshea** [comment]
I think it would be best to put everything in "rw" - I really don't want to move the db file again and deal with all the issues we had with it over the last two days :)

In any case, it would be best if this was worked on when nothing else is being done. Otherwise, the merge conflicts would be really difficult to sort out

**Comment by jakobschult** [comment]
Ok, would you like to do it? Right now I just do incremental changes, the issues are small, so right now I make sure, that I push directly after a commit.
If you find the time, just tell me a little bit in advance. Then I make sure that I have no changes, that are not pushed.
