### ISSUE TITLE
Invite email

### ISSUE THREAD

**Issue by jakobschult** [jakobschult/rwapp#32]
The links in the invite email are not lcickable for cahoo accounts. They just delete the href attribute

**Comment by jamesoshea** [comment]
Links look like this on my cool-guy hotmail account:

![Screenshot 2019-07-31 at 12 14 32](https://user-images.githubusercontent.com/22768409/62204124-d7deb180-b38c-11e9-8540-bf3bc85723c4.png)

**Comment by jamesoshea** [comment]
I will work on this with the folder merging while you're at the festival :)
