### ISSUE TITLE
Versuch, 2 Räder zu bestellen -->"SMTPAuthenticationError at /de/website/order"

### ISSUE THREAD

**Issue by Rueckenwind-Minka** [jakobschult/rwapp#40]

**Comment by Rueckenwind-Minka** [comment]
Unklar, was die Unterschiede bei den beiden Anfragen waren, die die unterschiedlichen Fehlermeldungen ausgelöst haben, waren.

**Comment by jakobschult** [comment]
Bei der Bestellung wird direkt eine Email  an den Besteller abgesendet. Da ich immer noch die Probleme mit der Authentifizierung bei Google hatte, ist die Bestellung zwar eingetragen worden, die Email konnte aber nicht abgeschickt werden weswegen es zu dieser unschönen Fehlermeldung kommt. Ich schicke die Emails jetzt nicht mehr über Google sondern über unseren Rückenwind Email anbieter. Ich hoffe dass klappt jetzt in Zukunft besser
