### ISSUE TITLE
Fahrrad-Spendenseite: "ValueError at /de/website/bike-donation" beim Versuch, Pickup-Angebot abzusenden und Buchstaben statt Zahlen bei "Anzahl" einzutragen.

### ISSUE THREAD

**Issue by Rueckenwind-Minka** [jakobschult/rwapp#42]

**Comment by Rueckenwind-Minka** [comment]
Eine entsprechende Fehlermeldung ("Bitte gib eine Zahl ein.") wäre angenehmer.

**Comment by jakobschult** [comment]
Es wird jetzt darauf hingewiesen, dass eine Zahl eingegeben werden muss. Der Fehler sollte nicht mehr auftreten
