### ISSUE TITLE
Registrierungen-Liste ist rechts abgeschnitten/kein Scrollbalken

### ISSUE THREAD

**Issue by Rueckenwind-Minka** [jakobschult/rwapp#43]

**Comment by Rueckenwind-Minka** [comment]
![Registrierungen_schmal](https://user-images.githubusercontent.com/56551144/66762821-f68e1800-eea6-11e9-9634-0df48663a4fe.jpg)

**Comment by jakobschult** [comment]
Also ich hab das jetzt so gelöst, dass die pslaten von rechts nach links abgeschnitten werden. Es wird aber ein plus zeichen angezeigt. Wenn man darauf klickt, werden alle spalten, auch die nicht sichtbaren unterineander angezeigt
