### ISSUE TITLE
Es müsste eine Obergrenze geben für abzuholende Bikes pro Workshop. Aktuell kann ich z. B. 19 auszugebende Räder für einen Workshop planen.

### ISSUE THREAD

**Issue by Rueckenwind-Minka** [jakobschult/rwapp#44]

**Comment by jakobschult** [comment]
Wenn jetzt die auf dem Workshop eingestellt Größe überschritten wird, wird der Workshop in der Liste der möglichen Workshops nicht mehr angezeigt. Eine Obergrenze kann man als Kapazität eingeben, wenn man den Workshop erstellt...
